name = "JuLox"
uuid = "5807206f-88c3-437c-9f39-ad0411e6d7b4"
authors = ["Tarun Vangani <reachtarunhere@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
